export const saveName = 'saveName'
export const updateUserData = 'updateUserData'
export const updateUserIsLoggedIn = 'updateUserIsLoggedIn'
export const updateLoading = 'updateLoading'
export const addMovie = 'addMovie'
export const removeMovie = 'removeMovie'
